# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "monthly"

  # Maintain dependencies for backend
  - package-ecosystem: "pip"
    directory: "/apps/backend"
    schedule:
      interval: "monthly"
