version: "3.9"

services:
  web:
    container_name: ${PROJECT_ID}_web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
    image: web:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - /opt/app
    ports:
      - ${PORT}:${PORT}
