repos:
  # https://github.com/pre-commit/pre-commit-hooks#pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  # Linting with Ruff
  # Ruff's pre-commit hook should be placed after other formatting tools, such as Black and isort, unless you enable autofix, in which case, Ruff's pre-commit hook should run before Black, isort, and other formatting tools, as Ruff's autofix behavior can output code changes that require reformatting.
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.263'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # https://pre-commit.com/#2-add-a-pre-commit-configuration
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11

  # Validating conventional pre-commit messages
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v2.1.1"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, script, style, deploy, doc]
