name: Deploy Frontend

on:
  push:
    tags:
      - '*'
    paths:
      - "apps/frontend/**"
      - ".github/**"
  release:
    types: [published]
    paths:
      - "apps/frontend/**"
      - ".github/**"

jobs:
  deploy-staging:
    name: Deploy Staging
    if: endsWith(github.ref, '/dev')
    uses: ./.github/workflows/_web-deploy.yml
    secrets: inherit
    with:
      ENVIRONMENT: "frontend-staging"
      GCP_RUN_CONFIG: "
      --memory 1Gi
      --cpu 1
      --timeout 40
      --concurrency 80
      --allow-unauthenticated
      --platform managed
      "

  deploy-production:
    name: Deploy Production
    if: endsWith(github.ref, '/main')
    uses: ./.github/workflows/_web-deploy.yml
    secrets: inherit
    with:
      ENVIRONMENT: "web-production"
      GCP_RUN_CONFIG: "
      --memory 2Gi
      --cpu 2
      --timeout 40
      --concurrency 80
      --allow-unauthenticated
      --platform managed
      "